version: "3.7"

networks:
  default:
    external:
      name: test-crm-network

services:
  web:
    build: docker/php
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/vtigercrm.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 5800:80

  db:
    build: docker/mysql
    restart: always
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./var/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vtiger
      - MYSQL_USER=vtiger
      - MYSQL_PASS=vtiger

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5880:8080
