version: "3"

networks:
  default:
    external:
      name: test-crm-network

services:
  web:
    build: docker/php
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/vtigercrm.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 5800:80

  db:
    build: docker/mysql
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./var/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: vtiger
      MYSQL_PASS: vtiger
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5880:8080
